language: python

jobs:
  include:
  - stage: curl
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s minimal
  -
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s shell
  -
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s server
  -
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s docker
  -
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s ansible
  -
    script: curl https://ls.gitcommit.fr -fsSL | sudo bash -s full
  - stage: wget
    script: wget -O - https://ls.gitcommit.fr | sudo bash -s minimal
