minimal:
  description: Install basic shell configuration
  programs:
    - vim
    - curl
    - zsh # For vim alias auto completion
  steps:
    - description: Installing vim configuration
      commands:
        - CP ./softwares/vim/.vimrc ~/.vimrc
        - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        - ["vim", "+silent", "+PlugInstall", "+qall"]
        - CHOWN ~/.vim
        - grep "^alias" ./softwares/zsh/.zshrc > ~/.zshenv
        - pip3 install pep8 jedi

shell:
  description: ZSH full shell configuration with oh my zsh
  dependencies:
    - minimal
  programs:
    - zsh
    - ranger
  steps:
    - description: Installing zsh custom configuration
      commands:
        - exit | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        - CP ./softwares/zsh/.zshrc ~/
        - grep "^alias" ~/.zshrc > ~/.zshenv
    - description: Apply custom ranger configuration
      commands:
        - mkdir -p ~/.config/ranger
        - CP ./softwares/ranger/rc.conf ~/.config/ranger/rc.conf
        - CHOWN ~/.config
  after_help: To switch default shell to zsh please run "chsh -s $(which zsh)"

server:
  description: Install server vim and zsh configuration
  dependencies:
    - minimal
    - shell
  steps:
    - description: Override default zsh prompt with server custom
      commands:
        - CP ./softwares/zsh/robbyrussell.zsh-theme ~/.oh-my-zsh/themes/robbyrussell.zsh-theme
  after_help: Do not forget to source zsh "source ~/.zshrc"

docker:
  description: Install docker and docker-compose
  programs:
    - curl
    - software-properties-common
    - apt-transport-https
  steps:
    - description: Docker configuration
      commands:
        - curl -fsSL get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - usermod -aG docker USER
        - curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose

ansible:
  description: Install ansible with required packages
  programs:
    - python-passlib
  steps:
    - description: Install passlib
      commands:
        - pip3 install -i https://pypi.python.org/simple/ --upgrade pip
        - pip3 install ansible

full:
  description: Install full shell configuration
  dependencies:
    - minimal
    - shell
